spring:
  application:
    name:my-blog
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${ROOT_USER}
    password: ${ROOT_PASS}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      #security:
      #user:
      #name: ${USER_NAME}
      #password: ${USER_PASSWORD}
      #roles: ${USER_ROLE}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-milliseconds: ${JWT_EXPIRATION}